api_platform:
    eager_loading:
        force_eager: false
    enable_docs: true
    mapping:
        paths:
            - "%kernel.project_dir%/config/api_platform" # yaml or xml directory configuration
            - "%kernel.project_dir%/src/Entity" # default configuration for attributes
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
    docs_formats:
        json: ["application/json"]
        jsonld: ["application/ld+json"]
        jsonopenapi: ["application/vnd.openapi+json"]
        html: ["text/html"]
    defaults:
        normalization_context:
            skip_null_values: false
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        extra_properties:
            #     standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
